# Generated by Django 4.1.5 on 2023-11-24 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('owner', models.CharField(max_length=100, null=True)),
                ('gender', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(null=True, upload_to='media/')),
                ('hostel_category', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('gender', models.CharField(max_length=100, null=True)),
                ('parent_name', models.CharField(max_length=100, null=True)),
                ('parent_contact', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room_alocate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Block_number', models.CharField(max_length=100, null=True)),
                ('Room_no', models.CharField(max_length=100, null=True)),
                ('Month_rent', models.CharField(max_length=100, null=True)),
                ('guest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Hostel.student')),
                ('hostel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Hostel.hostel')),
            ],
        ),
        migrations.CreateModel(
            name='room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=100, null=True)),
                ('room_type', models.CharField(max_length=100, null=True)),
                ('price', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(null=True, upload_to='media/')),
                ('hostel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Hostel.hostel')),
            ],
        ),
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Check_in', models.DateField(max_length=100, null=True)),
                ('Duration', models.CharField(max_length=100, null=True)),
                ('Total', models.IntegerField(max_length=100, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('payment', models.CharField(max_length=100, null=True)),
                ('guest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Hostel.student')),
                ('hostel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Hostel.hostel')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Hostel.room')),
            ],
        ),
    ]
