# Generated by Django 4.1.5 on 2023-11-24 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hostel', '0002_rename_price_room_block_remove_room_hostel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room_alocate',
            name='Block_number',
        ),
        migrations.RemoveField(
            model_name='room_alocate',
            name='Month_rent',
        ),
        migrations.RemoveField(
            model_name='room_alocate',
            name='Room_no',
        ),
        migrations.RemoveField(
            model_name='room_alocate',
            name='hostel',
        ),
        migrations.AddField(
            model_name='room_alocate',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Hostel.room'),
        ),
    ]
